service: aws-ts-lambda-sample

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - http:
          path: greetings/hello
          method: get
  goodbye:
    handler: src/functions/goodbye.handler
    events:
      - http:
          path: greetings/goodbye
          method: post

plugins:
  - serverless-plugin-typescript
#  - serverless-offline
